before:
  hooks:
    - go mod tidy -v
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64
      - amd64
      - mips64le
    main: ./cmd/agent
    binary: nezha-agent
universal_binaries:
  - name_template: "nezha-agent"
    replace: false
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "nezha-agent"
archives:
  - name_template: "nezha-agent_{{ .Os }}_{{ .Arch }}"
    files:
      - none*
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore"
      - Merge pull request
      - Merge branch
      - go mod tidy
